In [114]:
from datetime import datetime
from dateutil.relativedelta import relativedelta

import pandas as pd
pd.set_option("display.max_columns",30)
import requests

In [115]:
current_datetime=datetime.now() - relativedelta(months=2)
formatted_datetime=current_datetime.strftime("%Y-%m-%d")


url= (
    f"https://data.cityofchicago.org/api/v3/views/ajtu-isnz/query.json?app_token=ogjssL0qdXCJ16jANDq5lFDLc"
    f"&query=select * where trip_start_timestamp>='{formatted_datetime}T00:00:00' AND trip_start_timestamp<='{formatted_datetime}T23:59:59'"

)
response=requests.get(url)
data=response.json()

len(data)

23174

In [116]:
print ("https://data.cityofchicago.org/api/v3/views/ajtu-isnz/query.json?app_token=ogjssL0qdXCJ16jANDq5lFDLc"
    f"&query=select * where trip_start_timestamp>='"+formatted_datetime+"'")

https://data.cityofchicago.org/api/v3/views/ajtu-isnz/query.json?app_token=ogjssL0qdXCJ16jANDq5lFDLc&query=select * where trip_start_timestamp>='2025-09-26'

In [117]:
taxi_trips=pd.DataFrame(data)

taxi_trips.head()

,trip_id,taxi_id,trip_start_timestamp,trip_end_timestamp,trip_seconds,trip_miles,pickup_community_area,dropoff_community_area,fare,tips,tolls,extras,trip_total,payment_type,company,pickup_centroid_latitude,pickup_centroid_longitude,pickup_centroid_location,dropoff_centroid_latitude,dropoff_centroid_longitude,dropoff_centroid_location,:id,:version,:created_at,:updated_at,pickup_census_tract,dropoff_census_tract
0,5887b84e350521b3d1c9b31f6e9a5a4ef39be5d6,3618045f9110d4d88482266ade23659c1a50d32ac37f20...,2025-09-26T23:45:00.000,2025-09-27T00:00:00.000,783,2.99,22,16,10.39,3.31,0,0,14.2,Mobile,Tac - Yellow Cab Association,41.92276062,-87.699155343,"{'type': 'Point', 'coordinates': [-87.69915534...",41.953582125,-87.72345239,"{'type': 'Point', 'coordinates': [-87.72345239...",row-w32b~guyt.ft7m,rv-52c8-tce2-t9e9,2025-10-09T18:15:56.782Z,2025-10-09T18:15:56.782Z,NaN,NaN
1,006d64de27bc9d408ccb3fda78ff2d643334aee7,6c1e4e8e25a1b47575b359c5a0844cf23c50e540a86ecd...,2025-09-26T23:45:00.000,2025-09-26T23:45:00.000,630,1.39,8,8,8,3,0,0,11.5,Credit Card,Flash Cab,41.899602111,-87.633308037,"{'type': 'Point', 'coordinates': [-87.63330803...",41.899602111,-87.633308037,"{'type': 'Point', 'coordinates': [-87.63330803...",row-5aig.z528_ajd5,rv-tspa~efbc_d3ug,2025-10-09T18:15:56.782Z,2025-10-09T18:15:56.782Z,NaN,NaN
2,03fddd4b286099fe548254b40e2ee57bb6865375,8123ec5a70681a139fcd93fd477eec0ee05dda82987748...,2025-09-26T23:45:00.000,2025-09-27T00:00:00.000,751,4.18,8,6,15.77,0,0,0,16.27,Mobile,Globe Taxi,41.899602111,-87.633308037,"{'type': 'Point', 'coordinates': [-87.63330803...",41.944226601,-87.655998182,"{'type': 'Point', 'coordinates': [-87.65599818...",row-xswe_qdmz-ry8r,rv-y9xm.57mw~mi9c,2025-10-09T18:15:56.782Z,2025-10-09T18:15:56.782Z,NaN,NaN
3,043c9bde3029eb5a436ba33acfe379c89a49bf36,a0f44bc0a273e49230e4abe4d0a8d3a1e8305945f8fa0b...,2025-09-26T23:45:00.000,2025-09-27T00:15:00.000,1464,8.65,33,23,35.52,0,0,0,36.02,Mobile,Globe Taxi,41.857183858,-87.620334624,"{'type': 'Point', 'coordinates': [-87.62033462...",41.900069603,-87.720918238,"{'type': 'Point', 'coordinates': [-87.72091823...",row-gqws.23cs~dew6,rv-ywvv-6kjh-brs5,2025-10-09T18:15:56.782Z,2025-10-09T18:15:56.782Z,NaN,NaN
4,052b170224311f9b4f4eff285dcfe23a03fcc68d,d032016cdde07ebbac8ab34b98a534aed192e1c86d610f...,2025-09-26T23:45:00.000,2025-09-27T00:00:00.000,452,2.81,76,76,9.75,2,0,4,16.25,Credit Card,Medallion Leasin,41.980264315,-87.913624596,"{'type': 'Point', 'coordinates': [-87.91362459...",41.980264315,-87.913624596,"{'type': 'Point', 'coordinates': [-87.91362459...",row-memd~9u4e.246j,rv-xggw.vrvy_4rcu,2025-10-09T18:15:56.782Z,2025-10-09T18:15:56.782Z,NaN,NaN

In [118]:
taxi_trips.tail()

,trip_id,taxi_id,trip_start_timestamp,trip_end_timestamp,trip_seconds,trip_miles,pickup_community_area,dropoff_community_area,fare,tips,tolls,extras,trip_total,payment_type,company,pickup_centroid_latitude,pickup_centroid_longitude,pickup_centroid_location,dropoff_centroid_latitude,dropoff_centroid_longitude,dropoff_centroid_location,:id,:version,:created_at,:updated_at,pickup_census_tract,dropoff_census_tract
23169,2ec96e4a3512f35645d6b4e88df548e79c1abd87,1e320d8fd4e4610d538453cec33d541acf1bd1591a17ee...,2025-09-26T00:00:00.000,2025-09-26T00:15:00.000,874,6.81,3,32,24.52,0,0,0,25.02,Mobile,Sun Taxi,41.958055933,-87.660389456,"{'type': 'Point', 'coordinates': [-87.66038945...",41.880994471,-87.632746489,"{'type': 'Point', 'coordinates': [-87.63274648...",row-xcde-mwsp~dvd9,rv-47pg_er7n.2dnw,2025-10-09T18:15:56.782Z,2025-10-09T18:15:56.782Z,17031830700,17031839100
23170,2db30833ebb4fbc2c22b119f34f8c232851b3447,5e6ba3d77c1e1597624402bd204e81b4acbc3bdb103741...,2025-09-26T00:00:00.000,2025-09-26T00:15:00.000,720,6.4,76,10,18.25,4.5,0,4,26.75,Credit Card,Transit Administrative Center Inc,41.980264315,-87.913624596,"{'type': 'Point', 'coordinates': [-87.91362459...",41.985015101,-87.804532006,"{'type': 'Point', 'coordinates': [-87.80453200...",row-bzyu-bdfc-jbc9,rv-7g9c-x62t_kade,2025-10-09T18:15:56.782Z,2025-10-09T18:15:56.782Z,NaN,NaN
23171,116891f6e645aa8a310b74a3d20d31f36eaa4a79,8d75a4e15682364840d85e0f9f954e98b2703f4e252e88...,2025-09-26T00:00:00.000,2025-09-26T00:15:00.000,1020,10,56,28,26.25,6.15,0,4,36.4,Credit Card,Transit Administrative Center Inc,41.79259236,-87.769615453,"{'type': 'Point', 'coordinates': [-87.76961545...",41.874005383,-87.66351755,"{'type': 'Point', 'coordinates': [-87.66351754...",row-zbqn_ibns_pt24,rv-2dgy~efwd_ugfp,2025-10-09T18:15:56.782Z,2025-10-09T18:15:56.782Z,NaN,NaN
23172,28f2ee5349ed24f36a4040f83bf7f97546604fc5,af6fed00f40ccaeabf990aca8ad19696c7f4d989805167...,2025-09-26T00:00:00.000,2025-09-26T00:00:00.000,344,1.71,76,NaN,25,1,0,0,26.5,Credit Card,Sun Taxi,41.980264315,-87.913624596,"{'type': 'Point', 'coordinates': [-87.91362459...",NaN,NaN,NaN,row-e7ux_q6rk-4pz6,rv-q8a3-hs4q-7wi8,2025-10-09T18:15:56.782Z,2025-10-09T18:15:56.782Z,NaN,NaN
23173,25d1f1e46b73a098c2d566bdf9da91ef603e7838,b951b7af9a405d88275b77b6a04970bc2085661297b5e6...,2025-09-26T00:00:00.000,2025-09-26T00:30:00.000,1301,17.28,76,8,43,9.5,0,4,57,Credit Card,5 Star Taxi,41.97907082,-87.903039661,"{'type': 'Point', 'coordinates': [-87.90303966...",41.892042136,-87.63186395,"{'type': 'Point', 'coordinates': [-87.63186394...",row-ecnt~eh9a.52kb,rv-3skh.3xb3_ngrw,2025-10-09T18:15:56.782Z,2025-10-09T18:15:56.782Z,17031980000,17031081700

In [119]:
taxi_trips.sample(5)

,trip_id,taxi_id,trip_start_timestamp,trip_end_timestamp,trip_seconds,trip_miles,pickup_community_area,dropoff_community_area,fare,tips,tolls,extras,trip_total,payment_type,company,pickup_centroid_latitude,pickup_centroid_longitude,pickup_centroid_location,dropoff_centroid_latitude,dropoff_centroid_longitude,dropoff_centroid_location,:id,:version,:created_at,:updated_at,pickup_census_tract,dropoff_census_tract
3237,7d6ec4852a32be266da62d0048b7669893f0c8c3,46c4778c3a32454511f96752c509c608955e293da45dbf...,2025-09-26T19:45:00.000,2025-09-26T19:45:00.000,0,0,8,8,3.25,0,0,0,3.25,Cash,Transit Administrative Center Inc,41.892507781,-87.626214906,"{'type': 'Point', 'coordinates': [-87.62621490...",41.892507781,-87.626214906,"{'type': 'Point', 'coordinates': [-87.62621490...",row-rtxi-h7j5_4uar,rv-jykx_gyig_2kqp,2025-10-09T18:15:56.782Z,2025-10-09T18:15:56.782Z,17031081500,17031081500
4625,a9e0a47c1b6e8775782fd37514350a115f55d2f7,c52f389ae4d868380527db070d00352de61e235d5e3f87...,2025-09-26T18:45:00.000,2025-09-26T19:00:00.000,1220,6.46,32,38,19.75,0,0,0,19.75,Prcard,Flash Cab,41.878865584,-87.625192142,"{'type': 'Point', 'coordinates': [-87.62519214...",41.812948939,-87.617859676,"{'type': 'Point', 'coordinates': [-87.61785967...",row-2hce_qcha-r4tm,rv-abis~99b8_khv4,2025-10-09T18:15:56.782Z,2025-10-09T18:15:56.782Z,NaN,NaN
11198,b40ee6bcb7b0680c2bc38c5a08c566f4fbc3127b,a2c933ca0489813d4f5b49f79aa6c6b5701ef589bdc503...,2025-09-26T14:45:00.000,2025-09-26T15:00:00.000,641,1.61,32,8,8.5,1.82,0,0,10.82,Mobile,Taxicab Insurance Agency Llc,41.880994471,-87.632746489,"{'type': 'Point', 'coordinates': [-87.63274648...",41.907520075,-87.6266589,"{'type': 'Point', 'coordinates': [-87.62665890...",row-mgjx.exxr~cy5x,rv-724b~p49n-r4th,2025-10-09T18:15:56.782Z,2025-10-09T18:15:56.782Z,17031839100,17031080100
16782,654fa30f5065ca9caa8f3942703e189668fd5660,4972764cee12598f449342da6c1c3f3686f6e800184eba...,2025-09-26T11:15:00.000,2025-09-26T12:15:00.000,3591,17.97,76,32,46,10.1,0,4,60.6,Credit Card,Flash Cab,41.97907082,-87.903039661,"{'type': 'Point', 'coordinates': [-87.90303966...",41.877406123,-87.621971652,"{'type': 'Point', 'coordinates': [-87.62197165...",row-itrj_dixh_3dey,rv-pd4d_azte.jft3,2025-10-09T18:15:56.782Z,2025-10-09T18:15:56.782Z,17031980000,17031320400
1078,7c2953686b1af28bcd8ff0e796ad3d04c16e49e9,c81a672f30763423ddc7abac2b2e20a2f1ea045088ef77...,2025-09-26T22:00:00.000,2025-09-26T22:15:00.000,379,1.48,28,8,6.75,0,0,0,6.75,Cash,Flash Cab,41.874005383,-87.66351755,"{'type': 'Point', 'coordinates': [-87.66351754...",41.899602111,-87.633308037,"{'type': 'Point', 'coordinates': [-87.63330803...",row-enqs~cby9-hjvv,rv-yfnf_5xg2-ugs6,2025-10-09T18:15:56.782Z,2025-10-09T18:15:56.782Z,NaN,NaN

In [120]:
taxi_trips.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23174 entries, 0 to 23173
Data columns (total 27 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   trip_id                     23174 non-null  object
 1   taxi_id                     23174 non-null  object
 2   trip_start_timestamp        23174 non-null  object
 3   trip_end_timestamp          23173 non-null  object
 4   trip_seconds                23172 non-null  object
 5   trip_miles                  23174 non-null  object
 6   pickup_community_area       22524 non-null  object
 7   dropoff_community_area      21254 non-null  object
 8   fare                        23134 non-null  object
 9   tips                        23134 non-null  object
 10  tolls                       23134 non-null  object
 11  extras                      23134 non-null  object
 12  trip_total                  23134 non-null  object
 13  payment_type                23174 non-null  object
 14  company                     23174 non-null  object
 15  pickup_centroid_latitude    22525 non-null  object
 16  pickup_centroid_longitude   22525 non-null  object
 17  pickup_centroid_location    22525 non-null  object
 18  dropoff_centroid_latitude   21326 non-null  object
 19  dropoff_centroid_longitude  21326 non-null  object
 20  dropoff_centroid_location   21326 non-null  object
 21  :id                         23174 non-null  object
 22  :version                    23174 non-null  object
 23  :created_at                 23174 non-null  object
 24  :updated_at                 23174 non-null  object
 25  pickup_census_tract         10779 non-null  object
 26  dropoff_census_tract        10550 non-null  object
dtypes: object(27)
memory usage: 4.8+ MB

In [121]:
taxi_trips[taxi_trips["fare"].isna()].sample(5)

,trip_id,taxi_id,trip_start_timestamp,trip_end_timestamp,trip_seconds,trip_miles,pickup_community_area,dropoff_community_area,fare,tips,tolls,extras,trip_total,payment_type,company,pickup_centroid_latitude,pickup_centroid_longitude,pickup_centroid_location,dropoff_centroid_latitude,dropoff_centroid_longitude,dropoff_centroid_location,:id,:version,:created_at,:updated_at,pickup_census_tract,dropoff_census_tract
9158,eedf13c076abca7595f4e289fa1c59dc3e906216,58dd35601f224bc255e2d882fee540d5cabf30cabc55cf...,2025-09-26T16:00:00.000,2025-09-26T16:00:00.000,5,0,76,76,NaN,NaN,NaN,NaN,NaN,Cash,City Service,41.97907082,-87.903039661,"{'type': 'Point', 'coordinates': [-87.90303966...",41.97907082,-87.903039661,"{'type': 'Point', 'coordinates': [-87.90303966...",row-hkix~49uu_igvb,rv-5iqe_rafu_2eth,2025-10-09T18:15:56.782Z,2025-10-09T18:15:56.782Z,17031980000,17031980000
3745,d8c8d92ff6947a762ccdb8d179ac630ec882ba3a,64fef3c62cbbc9dd8c00e7e1cf6d29ea73d9ebdd758d4f...,2025-09-26T19:15:00.000,2025-09-26T21:00:00.000,6741,19.46,76,8,NaN,NaN,NaN,NaN,NaN,Cash,5 Star Taxi,41.97907082,-87.903039661,"{'type': 'Point', 'coordinates': [-87.90303966...",41.899155613,-87.626210532,"{'type': 'Point', 'coordinates': [-87.62621053...",row-x2u5_7gyu-sht6,rv-46j8_95tm~at5b,2025-10-09T18:15:56.782Z,2025-10-09T18:15:56.782Z,17031980000,17031081201
17425,66e944ce33e02b916f3dcfbe2766843a1ac205e7,2407ff99e367ceb469a8cc6663e6ad6ec51fb0f401d370...,2025-09-26T10:45:00.000,2025-09-26T11:15:00.000,1807,11.23,76,16,NaN,NaN,NaN,NaN,NaN,Cash,Chicago Independents,41.980264315,-87.913624596,"{'type': 'Point', 'coordinates': [-87.91362459...",41.953582125,-87.72345239,"{'type': 'Point', 'coordinates': [-87.72345239...",row-d8cn~wbxn-sawv,rv-285m.4av8_rhhy,2025-10-09T18:15:56.782Z,2025-10-09T18:15:56.782Z,NaN,NaN
10769,dd5bc115d46daef8fb4025b6a3c9837ea29e9187,c7e24b57c5ac5cc6b23bdaa7ad986c639f07680587bf71...,2025-09-26T15:00:00.000,2025-09-26T15:15:00.000,826,3.1,10,15,NaN,NaN,NaN,NaN,NaN,Cash,5 Star Taxi,41.985015101,-87.804532006,"{'type': 'Point', 'coordinates': [-87.80453200...",41.954027649,-87.763399032,"{'type': 'Point', 'coordinates': [-87.76339903...",row-bk3h_cbn6~fjtk,rv-c6b4-qeyt.w4zz,2025-10-09T18:15:56.782Z,2025-10-09T18:15:56.782Z,NaN,NaN
19040,337de6933f1b23fda722c47fd2270a8030060353,574b161e75a7dda9dc1f63751af8b83c982a3a76f5fc88...,2025-09-26T09:30:00.000,2025-09-26T10:00:00.000,2464,17.94,76,8,NaN,NaN,NaN,NaN,NaN,Cash,Taxicab Insurance Agency Llc,41.97907082,-87.903039661,"{'type': 'Point', 'coordinates': [-87.90303966...",41.89503345,-87.619710672,"{'type': 'Point', 'coordinates': [-87.61971067...",row-wjuu~dqyd~hpqt,rv-dyuu.r6eh~85wk,2025-10-09T18:15:56.782Z,2025-10-09T18:15:56.782Z,17031980000,17031081401

### Transformation/Deal vith NaN values

In [122]:
taxi_trips.drop(["pickup_census_tract","dropoff_census_tract"],axis=1,inplace=True)

In [123]:
taxi_trips.drop(["pickup_centroid_location","dropoff_centroid_location"],axis=1,inplace=True)

In [124]:
taxi_trips.dropna(inplace=True)   #ha valamelyik rekordban Nan van akkor az egész rekordot törli (adattisztítás)

In [125]:
taxi_trips.info()

<class 'pandas.core.frame.DataFrame'>
Index: 21003 entries, 0 to 23173
Data columns (total 23 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   trip_id                     21003 non-null  object
 1   taxi_id                     21003 non-null  object
 2   trip_start_timestamp        21003 non-null  object
 3   trip_end_timestamp          21003 non-null  object
 4   trip_seconds                21003 non-null  object
 5   trip_miles                  21003 non-null  object
 6   pickup_community_area       21003 non-null  object
 7   dropoff_community_area      21003 non-null  object
 8   fare                        21003 non-null  object
 9   tips                        21003 non-null  object
 10  tolls                       21003 non-null  object
 11  extras                      21003 non-null  object
 12  trip_total                  21003 non-null  object
 13  payment_type                21003 non-null  object
 14  company                     21003 non-null  object
 15  pickup_centroid_latitude    21003 non-null  object
 16  pickup_centroid_longitude   21003 non-null  object
 17  dropoff_centroid_latitude   21003 non-null  object
 18  dropoff_centroid_longitude  21003 non-null  object
 19  :id                         21003 non-null  object
 20  :version                    21003 non-null  object
 21  :created_at                 21003 non-null  object
 22  :updated_at                 21003 non-null  object
dtypes: object(23)
memory usage: 3.8+ MB

### Transformation/renaming

In [126]:
taxi_trips.rename(columns={"pickup_community_area":"pickup_community_area_id",
                           "dropoff_community_area":"dropoff_community_area_id"},inplace=True)

In [127]:
taxi_trips.columns

Index(['trip_id', 'taxi_id', 'trip_start_timestamp', 'trip_end_timestamp',
       'trip_seconds', 'trip_miles', 'pickup_community_area_id',
       'dropoff_community_area_id', 'fare', 'tips', 'tolls', 'extras',
       'trip_total', 'payment_type', 'company', 'pickup_centroid_latitude',
       'pickup_centroid_longitude', 'dropoff_centroid_latitude',
       'dropoff_centroid_longitude', ':id', ':version', ':created_at',
       ':updated_at'],
      dtype='object')

###Trasformation:create helper columns for weather and date dimension

In [128]:
taxi_trips["trip_start_timestamp"]=pd.to_datetime(taxi_trips["trip_start_timestamp"])

In [129]:
taxi_trips["datetime_for_weather"]=taxi_trips["trip_start_timestamp"].dt.floor("h")   
#az adatok negyedórásak, órássa alakítja hogy joinolni lehessen a weather adattal (ponots egyezés szükséges)
taxi_trips["datetime_for_weather"].sample(11)

315     2025-09-26 23:00:00
21160   2025-09-26 07:00:00
14988   2025-09-26 12:00:00
8022    2025-09-26 16:00:00
1906    2025-09-26 21:00:00
367     2025-09-26 23:00:00
3356    2025-09-26 19:00:00
3535    2025-09-26 19:00:00
4453    2025-09-26 19:00:00
944     2025-09-26 22:00:00
2835    2025-09-26 20:00:00
Name: datetime_for_weather, dtype: datetime64[ns]

taxi_trips["trip_start_date"]=pd.to_datetime(taxi_trips["trip_start_timestamp"]).dt.date
taxi_trips["trip_start_date"].sample(5)

### check: join taxi and weather data

In [131]:
current_datetime=datetime.now() - relativedelta(months=2)
formatted_datetime=current_datetime.strftime("%Y-%m-%d")

url="https://archive-api.open-meteo.com/v1/era5"

params={

    "latitude": 41.85,
    "longitude": -87.65,
    "start_date":formatted_datetime,
    "end_date":formatted_datetime,
    "hourly":"temperature_2m,wind_speed_10m,rain,precipitation"

}

response=requests.get(url,params=params)
data=response.json()

weather_data ={
    "datetime" : data["hourly"]["time"],
    "temperature" : data["hourly"]["temperature_2m"],
    "wind_speed" : data["hourly"]["wind_speed_10m"],
    "rain" : data["hourly"]["rain"],
    "precipitation" : data["hourly"]["precipitation"]
}

weather_df = pd.DataFrame(weather_data)
weather_df["datetime"] = pd.to_datetime(weather_df["datetime"] )

weather_df.sample(11)

              datetime  temperature  wind_speed  rain  precipitation
1  2025-09-26 01:00:00         17.6         3.1   0.0            0.0
17 2025-09-26 17:00:00         23.8         9.9   0.0            0.0
18 2025-09-26 18:00:00         24.9         9.0   0.0            0.0
23 2025-09-26 23:00:00         24.3         9.7   0.0            0.0
13 2025-09-26 13:00:00         14.9        10.0   0.0            0.0
0  2025-09-26 00:00:00         17.5         2.2   0.0            0.0
5  2025-09-26 05:00:00         16.0         4.4   0.0            0.0
8  2025-09-26 08:00:00         15.0         6.2   0.0            0.0
11 2025-09-26 11:00:00         14.4         8.0   0.0            0.0
16 2025-09-26 16:00:00         22.1         9.0   0.0            0.0
14 2025-09-26 14:00:00         16.8         7.7   0.0            0.0

In [132]:
taxi_trips_with_weather=taxi_trips.merge(weather_df,left_on="datetime_for_weather",right_on="datetime")
taxi_trips_with_weather.sample(11)

,trip_id,taxi_id,trip_start_timestamp,trip_end_timestamp,trip_seconds,trip_miles,pickup_community_area_id,dropoff_community_area_id,fare,tips,tolls,extras,trip_total,payment_type,company,pickup_centroid_latitude,pickup_centroid_longitude,dropoff_centroid_latitude,dropoff_centroid_longitude,:id,:version,:created_at,:updated_at,datetime_for_weather,trip_start_date,datetime,temperature,wind_speed,rain,precipitation
17253,46f6656044f1bf5e8613203ecdbf73e46d1484a7,6b6dc04e7b06da4f1dc50dee727d9ef2d1c2df22a009b4...,2025-09-26 09:30:00,2025-09-26T10:00:00.000,2141,15.03,56,7,39.5,9,0,5,54,Mobile,Sun Taxi,41.79259236,-87.769615453,41.922686284,-87.649488729,row-pn6s~yrtp~24rs,rv-mrcs.3n9m-6xhg,2025-10-09T18:15:56.782Z,2025-10-09T18:15:56.782Z,2025-09-26 09:00:00,2025-09-26,2025-09-26 09:00:00,14.7,6.3,0.0,0.0
20758,b346133d754e406cf863d4c78c772686c78bea0b,b3ee94a13b61037620cbbfc6a4a106d2ad628a06f0988f...,2025-09-26 00:45:00,2025-09-26T00:45:00.000,180,0.4,8,8,4.5,0,0,2,6.5,Cash,Transit Administrative Center Inc,41.899602111,-87.633308037,41.899602111,-87.633308037,row-4pse_uh6i-t9pp,rv-5hwi_jd84_v88b,2025-10-09T18:15:56.782Z,2025-10-09T18:15:56.782Z,2025-09-26 00:00:00,2025-09-26,2025-09-26 00:00:00,17.5,2.2,0.0,0.0
4688,3d6e089be0933c6143825b00d4d53da0d4083c78,4e2f65a7aa0041c47a12b57b49aa592b2145daacdfe37a...,2025-09-26 18:30:00,2025-09-26T18:30:00.000,0,0,32,32,3.25,0,0,0,3.25,Cash,Transit Administrative Center Inc,41.884987192,-87.620992913,41.884987192,-87.620992913,row-tvss.jjiw~3ha4,rv-mjcs.zaep_dwpi,2025-10-09T18:15:56.782Z,2025-10-09T18:15:56.782Z,2025-09-26 18:00:00,2025-09-26,2025-09-26 18:00:00,24.9,9.0,0.0,0.0
3470,5b7d5007a531d5aaf30b86a7a5dae59e1c5dd5b8,d41e198fbed96bdbe8649a6c626cfeb16e5f82ca39a0c7...,2025-09-26 19:15:00,2025-09-26T19:45:00.000,1715,8.73,32,4,31.38,0,0,0,31.88,Mobile,Medallion Leasin,41.878865584,-87.625192142,41.975170943,-87.687515515,row-jt9f.dmkd.b2za,rv-473j-h795_9uc4,2025-10-09T18:15:56.782Z,2025-10-09T18:15:56.782Z,2025-09-26 19:00:00,2025-09-26,2025-09-26 19:00:00,25.6,8.6,0.0,0.0
1034,ea708a1176ee752ec569ab9d059dbbcd7f962e14,cb80f58820478e379627f16b373d5e29ca5343b9307b65...,2025-09-26 21:45:00,2025-09-26T22:00:00.000,1077,4.42,8,33,15.25,3.15,0,0,18.9,Credit Card,City Service,41.899155613,-87.626210532,41.859349715,-87.617358006,row-kyai.f5ed.94ud,rv-gikz.vtuf-tgbv,2025-10-09T18:15:56.782Z,2025-10-09T18:15:56.782Z,2025-09-26 21:00:00,2025-09-26,2025-09-26 21:00:00,25.9,9.2,0.0,0.0
11122,9c83254270e26b7526c36c6f321fa051fcbe8748,053486cd912ae399d28c26d6976cf507140df78ec57d09...,2025-09-26 14:00:00,2025-09-26T14:15:00.000,576,1.08,8,8,8.5,2.4,0,0,11.4,Mobile,Sun Taxi,41.892042136,-87.63186395,41.899155613,-87.626210532,row-xmm5_rxa8_zd77,rv-662z_exn9.kis3,2025-10-09T18:15:56.782Z,2025-10-09T18:15:56.782Z,2025-09-26 14:00:00,2025-09-26,2025-09-26 14:00:00,16.8,7.7,0.0,0.0
7915,cfad2b816318941fa9bacbff1ef90a1665e4bab6,be5db5106829df724988f3e5da5f59672e95972e57ec75...,2025-09-26 16:15:00,2025-09-26T17:45:00.000,4675,25.64,76,41,64.5,13.8,0,4,82.8,Credit Card,Star North Taxi Management Llc,41.97907082,-87.903039661,41.790506261,-87.583143717,row-t5ia-zyt6_vy3g,rv-5maj-u67t~47fx,2025-10-09T18:15:56.782Z,2025-10-09T18:15:56.782Z,2025-09-26 16:00:00,2025-09-26,2025-09-26 16:00:00,22.1,9.0,0.0,0.0
18158,2fe9fcc028612e5976d660e0ff9f6f8d39df0d6e,259d38cfdbc9ac6f9bb01f0df740e0ddf4a631a70bbdd6...,2025-09-26 08:45:00,2025-09-26T08:45:00.000,360,0.8,32,32,6,2,0,1,9,Credit Card,Taxicab Insurance Agency LLC,41.880994471,-87.632746489,41.880994471,-87.632746489,row-9ywj-u4v6.wrxt,rv-yg7p_93rb_365f,2025-10-09T18:15:56.782Z,2025-10-09T18:15:56.782Z,2025-09-26 08:00:00,2025-09-26,2025-09-26 08:00:00,15.0,6.2,0.0,0.0
2805,a8443ff28ded79740c7c002c8dac483a112be5d1,5c05237ba3c9c58aeafc5622ebe12d6c9a7f40234ef36f...,2025-09-26 19:45:00,2025-09-26T19:45:00.000,673,0.5,8,8,7,0,0,0,7,Cash,Flash Cab,41.89503345,-87.619710672,41.892507781,-87.626214906,row-gsz7-grym~z2qt,rv-ye8y.hji2_5kx2,2025-10-09T18:15:56.782Z,2025-10-09T18:15:56.782Z,2025-09-26 19:00:00,2025-09-26,2025-09-26 19:00:00,25.6,8.6,0.0,0.0
1479,641bd52f0a05ef4d6febfb4f3f0c0f0ea7dd309c,4e2f65a7aa0041c47a12b57b49aa592b2145daacdfe37a...,2025-09-26 21:15:00,2025-09-26T21:30:00.000,600,1,8,8,7,0,0,1,8,Cash,Transit Administrative Center Inc,41.899602111,-87.633308037,41.899602111,-87.633308037,row-3i7s-c3u8~gsbz,rv-gj4k-8rzy-jnyh,2025-10-09T18:15:56.782Z,2025-10-09T18:15:56.782Z,2025-09-26 21:00:00,2025-09-26,2025-09-26 21:00:00,25.9,9.2,0.0,0.0
7957,aeb844d66171c577343cf1c865d5c4c766cf276c,4489496317d593d220fd48f54f9db2732a9a1365fb5206...,2025-09-26 16:15:00,2025-09-26T16:30:00.000,669,0.8,8,8,7,0,0,0,7.5,Mobile,Sun Taxi,41.900221297,-87.629105186,41.892042136,-87.63186395,row-rk79-7fti~hnqt,rv-bnqg_mdbb_wuxt,2025-10-09T18:15:56.782Z,2025-10-09T18:15:56.782Z,2025-09-26 16:00:00,2025-09-26,2025-09-26 16:00:00,22.1,9.0,0.0,0.0

### Trasformation data type conversions

In [133]:
taxi_trips.info()

<class 'pandas.core.frame.DataFrame'>
Index: 21003 entries, 0 to 23173
Data columns (total 25 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   trip_id                     21003 non-null  object
 1   taxi_id                     21003 non-null  object
 2   trip_start_timestamp        21003 non-null  datetime64[ns]
 3   trip_end_timestamp          21003 non-null  object
 4   trip_seconds                21003 non-null  object
 5   trip_miles                  21003 non-null  object
 6   pickup_community_area_id    21003 non-null  object
 7   dropoff_community_area_id   21003 non-null  object
 8   fare                        21003 non-null  object
 9   tips                        21003 non-null  object
 10  tolls                       21003 non-null  object
 11  extras                      21003 non-null  object
 12  trip_total                  21003 non-null  object
 13  payment_type                21003 non-null  object
 14  company                     21003 non-null  object
 15  pickup_centroid_latitude    21003 non-null  object
 16  pickup_centroid_longitude   21003 non-null  object
 17  dropoff_centroid_latitude   21003 non-null  object
 18  dropoff_centroid_longitude  21003 non-null  object
 19  :id                         21003 non-null  object
 20  :version                    21003 non-null  object
 21  :created_at                 21003 non-null  object
 22  :updated_at                 21003 non-null  object
 23  datetime_for_weather        21003 non-null  datetime64[ns]
 24  trip_start_date             21003 non-null  object
dtypes: datetime64[ns](2), object(23)
memory usage: 4.2+ MB

In [134]:
taxi_trips_original=taxi_trips.copy()

In [135]:
data_types={
    "trip_seconds":"int32",
    "trip_miles":"float",
    "pickup_community_area_id":"int8",
    "dropoff_community_area_id":"int8",
    "fare":"float",
    "tips":"float",
    "tolls":"float",
    "extras":"float",
    "trip_total":"float",
    "pickup_centroid_latitude":"float",
    "pickup_centroid_longitude":"float",
    "dropoff_centroid_latitude":"float",
    "dropoff_centroid_longitude":"float",
}

taxi_trips=taxi_trips.astype(data_types)

In [136]:
taxi_trips.info()

<class 'pandas.core.frame.DataFrame'>
Index: 21003 entries, 0 to 23173
Data columns (total 25 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   trip_id                     21003 non-null  object
 1   taxi_id                     21003 non-null  object
 2   trip_start_timestamp        21003 non-null  datetime64[ns]
 3   trip_end_timestamp          21003 non-null  object
 4   trip_seconds                21003 non-null  int32
 5   trip_miles                  21003 non-null  float64
 6   pickup_community_area_id    21003 non-null  int8
 7   dropoff_community_area_id   21003 non-null  int8
 8   fare                        21003 non-null  float64
 9   tips                        21003 non-null  float64
 10  tolls                       21003 non-null  float64
 11  extras                      21003 non-null  float64
 12  trip_total                  21003 non-null  float64
 13  payment_type                21003 non-null  object
 14  company                     21003 non-null  object
 15  pickup_centroid_latitude    21003 non-null  float64
 16  pickup_centroid_longitude   21003 non-null  float64
 17  dropoff_centroid_latitude   21003 non-null  float64
 18  dropoff_centroid_longitude  21003 non-null  float64
 19  :id                         21003 non-null  object
 20  :version                    21003 non-null  object
 21  :created_at                 21003 non-null  object
 22  :updated_at                 21003 non-null  object
 23  datetime_for_weather        21003 non-null  datetime64[ns]
 24  trip_start_date             21003 non-null  object
dtypes: datetime64[ns](2), float64(10), int32(1), int8(2), object(10)
memory usage: 3.8+ MB

### Memory usage

In [137]:
orig_mem=taxi_trips_original.memory_usage(deep=True).sum()
opt_mem=taxi_trips.memory_usage(deep=True).sum()

diff=(orig_mem-opt_mem)/orig_mem*100
print(f"Original:{orig_mem:,} bytes")
print(f"Optimized:{opt_mem:,} bytes")
print(f"Memory reduced by:{diff:.2f}%")

Original:31,776,981 bytes
Optimized:18,708,917 bytes
Memory reduced by:41.12%

### Sanity check

In [138]:
taxi_trips.describe()

,trip_start_timestamp,trip_seconds,trip_miles,pickup_community_area_id,dropoff_community_area_id,fare,tips,tolls,extras,trip_total,pickup_centroid_latitude,pickup_centroid_longitude,dropoff_centroid_latitude,dropoff_centroid_longitude,datetime_for_weather
count,21003,21003.000000,21003.000000,21003.000000,21003.000000,21003.000000,21003.000000,21003.000000,21003.000000,21003.000000,21003.000000,21003.000000,21003.000000,21003.000000,21003
mean,2025-09-26 14:14:46.759034624,1256.093939,5.738718,30.584202,25.041708,20.747713,2.307297,0.007444,1.180096,24.537149,41.897005,-87.679706,41.891547,-87.655905,2025-09-26 13:52:17.380374272
min,2025-09-26 00:00:00,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,41.660136,-87.913625,41.660136,-87.913625,2025-09-26 00:00:00
25%,2025-09-26 10:45:00,481.000000,1.110000,8.000000,8.000000,8.500000,0.000000,0.000000,0.000000,10.000000,41.878866,-87.663518,41.878866,-87.657233,2025-09-26 10:00:00
50%,2025-09-26 14:30:00,850.000000,2.590000,28.000000,28.000000,13.430000,0.000000,0.000000,0.000000,15.300000,41.892508,-87.633308,41.892042,-87.633308,2025-09-26 14:00:00
75%,2025-09-26 18:00:00,1657.000000,10.290000,38.000000,32.000000,30.500000,3.000000,0.000000,1.000000,32.000000,41.943155,-87.625192,41.907520,-87.622173,2025-09-26 18:00:00
max,2025-09-26 23:45:00,67341.000000,49.110000,77.000000,77.000000,4188.000000,60.000000,12.000000,761.000000,4188.000000,42.009623,-87.534903,42.009623,-87.534903,2025-09-26 23:00:00
std,NaN,1689.151330,6.217482,24.377823,20.185516,33.194562,3.853394,0.179433,6.511650,35.493453,0.059797,0.098692,0.055162,0.066337,NaN

In [139]:
taxi_trips[taxi_trips["trip_end_timestamp"]==taxi_trips["trip_end_timestamp"].max()]

,trip_id,taxi_id,trip_start_timestamp,trip_end_timestamp,trip_seconds,trip_miles,pickup_community_area_id,dropoff_community_area_id,fare,tips,tolls,extras,trip_total,payment_type,company,pickup_centroid_latitude,pickup_centroid_longitude,dropoff_centroid_latitude,dropoff_centroid_longitude,:id,:version,:created_at,:updated_at,datetime_for_weather,trip_start_date
3432,c31c7254060f366cfa39ba7c72b01aa2d7844e63,cb3bd991c2f7932527ef9d5f341674dfba53745f25fe3e...,2025-09-26 19:30:00,2025-09-27T13:00:00.000,63044,8.73,28,69,23.5,0.0,0.0,0.0,23.5,Cash,Blue Ribbon Taxi Association,41.874005,-87.663518,41.763247,-87.616134,row-csau~dmid_szuf,rv-4a6p_xuir_qs3b,2025-10-09T18:15:56.782Z,2025-10-09T18:15:56.782Z,2025-09-26 19:00:00,2025-09-26

In [140]:
taxi_trips[taxi_trips["trip_seconds"]==taxi_trips["trip_seconds"].max()]

,trip_id,taxi_id,trip_start_timestamp,trip_end_timestamp,trip_seconds,trip_miles,pickup_community_area_id,dropoff_community_area_id,fare,tips,tolls,extras,trip_total,payment_type,company,pickup_centroid_latitude,pickup_centroid_longitude,dropoff_centroid_latitude,dropoff_centroid_longitude,:id,:version,:created_at,:updated_at,datetime_for_weather,trip_start_date
5900,bef4fbe286eddcab707ab6d6c19f3d9488e61afc,ce54c7c28cb19a2cea84881f18dba17780375cc59a8c8f...,2025-09-26 18:00:00,2025-09-27T12:45:00.000,67341,11.07,6,76,67.75,0.0,0.0,0.0,67.75,Cash,Taxicab Insurance Agency Llc,41.94914,-87.656804,41.979071,-87.90304,row-y7td.eep8_34wz,rv-bphv_cew8~n9kf,2025-10-09T18:15:56.782Z,2025-10-09T18:15:56.782Z,2025-09-26 18:00:00,2025-09-26

In [141]:
taxi_trips[taxi_trips["fare"]==taxi_trips["fare"].max()]

,trip_id,taxi_id,trip_start_timestamp,trip_end_timestamp,trip_seconds,trip_miles,pickup_community_area_id,dropoff_community_area_id,fare,tips,tolls,extras,trip_total,payment_type,company,pickup_centroid_latitude,pickup_centroid_longitude,dropoff_centroid_latitude,dropoff_centroid_longitude,:id,:version,:created_at,:updated_at,datetime_for_weather,trip_start_date
11966,bed04cfe4ab77a897a1e7e3bf4b83595109d8a87,bc8f828bfabea08242e8ba5d7283722378869f674da074...,2025-09-26 14:15:00,2025-09-26T14:45:00.000,1229,0.0,43,33,4188.0,0.0,0.0,0.0,4188.0,Cash,Tac - Yellow Cab Association,41.761578,-87.572782,41.857184,-87.620335,row-ztq2_6s4d~758x,rv-hyk2_ewan_j6bm,2025-10-09T18:15:56.782Z,2025-10-09T18:15:56.782Z,2025-09-26 14:00:00,2025-09-26

### payment type dimension

In [142]:
taxi_trips["payment_type"].unique()

array(['Mobile', 'Credit Card', 'Prcard', 'Cash', 'Unknown', 'No Charge',
       'Dispute'], dtype=object)

In [143]:
dim_payment_type=taxi_trips["payment_type"].drop_duplicates().reset_index(drop=True)
dim_payment_type

0         Mobile
1    Credit Card
2         Prcard
3           Cash
4        Unknown
5      No Charge
6        Dispute
Name: payment_type, dtype: object

In [144]:
for i in range(1,len(dim_payment_type)+1):
    print (i)

1
2
3
4
5
6
7

In [145]:
dim_payment_type=pd.DataFrame(
    {"payment_type_id":range(1,len(dim_payment_type)+1),
     "payment_type":dim_payment_type
    }
)
dim_payment_type

   payment_type_id payment_type
0                1       Mobile
1                2  Credit Card
2                3       Prcard
3                4         Cash
4                5      Unknown
5                6    No Charge
6                7      Dispute

### Company dimension

In [146]:
dim_company=taxi_trips["company"].drop_duplicates().reset_index(drop=True)
dim_company=pd.DataFrame(
    {"company_id":range(1,len(dim_company)+1),
     "company":dim_company
    }
)
dim_company

    company_id                               company
0            1          Tac - Yellow Cab Association
1            2                             Flash Cab
2            3                            Globe Taxi
3            4                      Medallion Leasin
4            5                  Chicago Independents
5            6          Blue Ribbon Taxi Association
6            7            Tac - Checker Cab Dispatch
7            8                           5 Star Taxi
8            9     Transit Administrative Center Inc
9           10                          City Service
10          11                              Sun Taxi
11          12          Taxicab Insurance Agency Llc
12          13           Choice Taxi Association Inc
13          14         Chicago City Taxi Association
14          15         Taxicab Insurance Agency  LLC
15          16  Patriot Taxi Dba Peace Taxi Associat
16          17         312 Medallion Management Corp
17          18                       Chicago Taxicab
18          19           3556 - 36214 RC Andrews Cab
19          20        Star North Taxi Management Llc
20          21                               Top Cab
21          22                           Wolley Taxi
22          23                            Setare Inc
23          24        Tac - American United Dispatch
24          25                Tac - Yellow Non Color
25          26           Tac - Blue Diamond Dispatch
26          27                 Koam Taxi Association
27          28            5167 - 71969 5167 Taxi Inc
28          29                             U Taxicab
29          30           6574 - Babylon Express Inc.
30          31                     Metro Jet Taxi A.
31          32          4053 - 40193 Adwar H. Nikola

### merging back to the fact table

In [147]:
fact_taxi_trips=taxi_trips.merge(dim_payment_type,on="payment_type")
fact_taxi_trips=fact_taxi_trips.merge(dim_company,on="company")
fact_taxi_trips.sample(5)

,trip_id,taxi_id,trip_start_timestamp,trip_end_timestamp,trip_seconds,trip_miles,pickup_community_area_id,dropoff_community_area_id,fare,tips,tolls,extras,trip_total,payment_type,company,pickup_centroid_latitude,pickup_centroid_longitude,dropoff_centroid_latitude,dropoff_centroid_longitude,:id,:version,:created_at,:updated_at,datetime_for_weather,trip_start_date,payment_type_id,company_id
9650,fbbd29ce6340ee597273fbaa36241accf9b2217c,da6f829d43ef9293b94c21a502d12c9a48b2a7d7b6a886...,2025-09-26 15:00:00,2025-09-26T15:15:00.000,1018,2.70,7,32,11.75,2.00,0.0,0.0,14.25,Credit Card,Koam Taxi Association,41.922083,-87.634156,41.880994,-87.632746,row-pwx7~hex6.c56t,rv-t4ig-vprg.u7pc,2025-10-09T18:15:56.782Z,2025-10-09T18:15:56.782Z,2025-09-26 15:00:00,2025-09-26,2,27
4442,d2c4d1454c5ddc889b6c81dd9118ddc3f4c34234,3577d72a8bf30406c1346a5e178b7f3a0ce8e1f966f59a...,2025-09-26 18:30:00,2025-09-26T18:30:00.000,240,0.90,8,8,5.75,0.00,0.0,2.0,7.75,Cash,Transit Administrative Center Inc,41.891972,-87.612945,41.890922,-87.618868,row-esrt-v954.vst8,rv-ziu9_geuj_hr4e,2025-10-09T18:15:56.782Z,2025-10-09T18:15:56.782Z,2025-09-26 18:00:00,2025-09-26,4,9
14998,f2656acdd6512f402f973da7354e3a61d2e973c5,67b8283f19334dd9f9e2d36e9a9fbd2c4f0da9dd3390bf...,2025-09-26 11:15:00,2025-09-26T11:15:00.000,480,1.80,33,32,8.25,2.00,0.0,0.0,10.25,Credit Card,Transit Administrative Center Inc,41.857184,-87.620335,41.878866,-87.625192,row-mgxi~676j.rejj,rv-g26y_h6nk.ycxh,2025-10-09T18:15:56.782Z,2025-10-09T18:15:56.782Z,2025-09-26 11:00:00,2025-09-26,2,9
14730,ca5ac3863736df9e130464d2534062da7d134555,79ed9ac0abaaf810157e54af0f923489a9560aa0310479...,2025-09-26 11:30:00,2025-09-26T11:45:00.000,736,1.66,8,28,9.00,3.00,0.0,0.0,12.50,Credit Card,Taxicab Insurance Agency Llc,41.890922,-87.618868,41.879255,-87.642649,row-vwzf_b8bt~iyp6,rv-zucv-ha88.bm76,2025-10-09T18:15:56.782Z,2025-10-09T18:15:56.782Z,2025-09-26 11:00:00,2025-09-26,2,12
14804,8fc039cfd017fd4ef28e8195e42f6bdbd0f66fdb,ed5ea8aa629c794c3ecfef8ef582d7b6077a7a4c25e000...,2025-09-26 11:30:00,2025-09-26T12:30:00.000,3154,18.68,32,76,48.25,9.75,0.0,0.0,58.50,Credit Card,Chicago Independents,41.884987,-87.620993,41.979071,-87.903040,row-r4ex.e33e.iiz8,rv-b5m8_hvvq~7be2,2025-10-09T18:15:56.782Z,2025-10-09T18:15:56.782Z,2025-09-26 11:00:00,2025-09-26,2,5

In [148]:
fact_taxi_trips.drop(["payment_type","company"],axis=1,inplace=True)
fact_taxi_trips.sample(5)

,trip_id,taxi_id,trip_start_timestamp,trip_end_timestamp,trip_seconds,trip_miles,pickup_community_area_id,dropoff_community_area_id,fare,tips,tolls,extras,trip_total,pickup_centroid_latitude,pickup_centroid_longitude,dropoff_centroid_latitude,dropoff_centroid_longitude,:id,:version,:created_at,:updated_at,datetime_for_weather,trip_start_date,payment_type_id,company_id
457,f85a267ca412d182f3dcea31041cffe343872428,15bd3003357b5782fa70b8adcb0690262b47d1ef234c12...,2025-09-26 22:45:00,2025-09-26T22:45:00.000,373,1.46,41,69,8.16,0.0,0.0,0.0,8.66,41.794090,-87.592311,41.763247,-87.616134,row-fh6v~b7uv-75dc,rv-rdt9.ctm6.4q2s,2025-10-09T18:15:56.782Z,2025-10-09T18:15:56.782Z,2025-09-26 22:00:00,2025-09-26,1,12
6966,66e70c5068e7b25bc658f9feea9b46c94f3592c0,fd4c6f99a5a84e4ee477beb7cc4ca29db1943fdd145c8c...,2025-09-26 17:00:00,2025-09-26T17:15:00.000,1164,1.86,8,28,11.77,0.0,0.0,0.0,12.27,41.895033,-87.619711,41.885281,-87.657233,row-qkt4~suye_fri4,rv-buj4-nvf2.m464,2025-10-09T18:15:56.782Z,2025-10-09T18:15:56.782Z,2025-09-26 17:00:00,2025-09-26,1,5
15027,d5f41dec27b12e6cf22c62c18184a4d3780ca31a,6e0a0360a9107f3cc0064a80f49f33a7f53e8aa6232d66...,2025-09-26 11:15:00,2025-09-26T11:15:00.000,396,1.34,33,32,9.14,0.0,0.0,0.0,9.64,41.859350,-87.617358,41.884987,-87.620993,row-9m3b_fj4s.td9t,rv-y8uh.wvvs~mxva,2025-10-09T18:15:56.782Z,2025-10-09T18:15:56.782Z,2025-09-26 11:00:00,2025-09-26,1,2
18351,766cf70ee7353be977d6f44ff32839c3dfaf7cd1,6d869f9e0b9021de42c3fe26664b8f87e0da69245bc002...,2025-09-26 08:30:00,2025-09-26T08:45:00.000,900,2.70,32,28,11.00,0.0,0.0,6.0,17.00,41.880994,-87.632746,41.879255,-87.642649,row-ep72-9pei-2r9q,rv-ygax-xr3p_eswa,2025-10-09T18:15:56.782Z,2025-10-09T18:15:56.782Z,2025-09-26 08:00:00,2025-09-26,4,9
20402,cac61f2e37436ec9b39cb28e9ba7ffa9162120bd,511fc9cb2efb73fcb0fa664156beafbfcef79e71de57bf...,2025-09-26 04:45:00,2025-09-26T05:15:00.000,1941,17.44,32,76,43.50,0.0,0.0,0.0,44.00,41.884987,-87.620993,41.979071,-87.903040,row-qg3i_4dfg-v437,rv-w244~i5bm.fvbb,2025-10-09T18:15:56.782Z,2025-10-09T18:15:56.782Z,2025-09-26 04:00:00,2025-09-26,2,11

In [150]:
dim_payment_type.to_csv("dim_payment_type.csv",index=False)
dim_company.to_csv("dim_company.csv",index=False)

### Create update loogic for dimension tables

In [159]:
dim_payment_type=taxi_trips["payment_type"].drop_duplicates().reset_index(drop=True)
dim_payment_type=pd.DataFrame(
    {"payment_type_id":range(1,len(dim_payment_type)+1),
     "payment_type":dim_payment_type
    }
)
dummy_payment_type_data=[
    {"payment_type":"Credit Card"},
    {"payment_type":"x"},
    {"payment_type":"y"},
    {"payment_type":"x"},
]
dummy_payment_type_data_df=pd.DataFrame(dummy_payment_type_data)

dummy_payment_type_data_df
#modellezük a holnap letöltött adatok között megjelenő esetleges új adatelemeket mesterséges duplikációval ( új payment type)

  payment_type
0  Credit Card
1            x
2            y
3            x

In [ ]:
todays_payment_types=pd.DataFrame(dummy_payment_type_data_df["payment_type"].unique(),columns=["payment_type"])
#kivesszük az ismétlődést és az oszlop neve payment type lesz
new_payment_type=todays_payment_types[~todays_payment_types["payment_type"].isin(dim_payment_type["payment_type"])]
#tilde jel a pythonban a NOT, tehát nincs benne az mai adat a meglévőben azt teszi az újba

new_payment_type

  payment_type
1            x
2            y

In [165]:
if not new_payment_type.empty:
    max_id=dim_payment_type["payment_type_id"].max()
    new_payment_type["payment_type_id"]=range(max_id+1,max_id+1+len(new_payment_type))
    dim_payment_type=pd.concat([dim_payment_type,new_payment_type],ignore_index=True)

dim_payment_type

C:\Users\dmcszs87\AppData\Local\Temp\ipykernel_10984\2083938348.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_payment_type["payment_type_id"]=range(max_id+1,max_id+1+len(new_payment_type))

   payment_type_id payment_type
0                1       Mobile
1                2  Credit Card
2                3       Prcard
3                4         Cash
4                5      Unknown
5                6    No Charge
6                7      Dispute
7                8            x
8                9            y

In [ ]:
#testing the logic with different data


dummy_payment_type_data=[
    {"payment_type":"Credit Card"},
    {"payment_type":"x"},
    {"payment_type":"z"},
    {"payment_type":"z"},
]
dummy_payment_type_data_df=pd.DataFrame(dummy_payment_type_data)

todays_payment_types=pd.DataFrame(dummy_payment_type_data_df["payment_type"].unique(),columns=["payment_type"])

new_payment_type=todays_payment_types[~todays_payment_types["payment_type"].isin(dim_payment_type["payment_type"])]


if not new_payment_type.empty:
    max_id=dim_payment_type["payment_type_id"].max()
    new_payment_type["payment_type_id"]=range(max_id+1,max_id+1+len(new_payment_type))
    dim_payment_type=pd.concat([dim_payment_type,new_payment_type],ignore_index=True)

dim_payment_type

   payment_type_id payment_type
0                1       Mobile
1                2  Credit Card
2                3       Prcard
3                4         Cash
4                5      Unknown
5                6    No Charge
6                7      Dispute
7                8            x
8                9            y
9               10            z

In [168]:
dim_company.tail()

    company_id                       company
27          28    5167 - 71969 5167 Taxi Inc
28          29                     U Taxicab
29          30   6574 - Babylon Express Inc.
30          31             Metro Jet Taxi A.
31          32  4053 - 40193 Adwar H. Nikola

In [169]:
dim_company=taxi_trips["company"].drop_duplicates().reset_index(drop=True)
dim_company=pd.DataFrame(
    {"company_id":range(1,len(dim_company)+1),
     "company":dim_company
    }
)
dummy_company_data=[
    {"company":"4053 - 40193 Adwar H. Nikola"},
    {"company":"x"},
    {"company":"y"},
    {"company":"x"},
]
dummy_company_data_df=pd.DataFrame(dummy_company_data)

todays_company=pd.DataFrame(dummy_company_data_df["company"].unique(),columns=["company"])

new_company=todays_company[~todays_company["company"].isin(dim_company["company"])]

if not new_company.empty:
    max_id=dim_company["company_id"].max()
    new_company["company_id"]=range(max_id+1,max_id+1+len(new_company))
    dim_company=pd.concat([dim_company,new_company],ignore_index=True)

dim_company

C:\Users\dmcszs87\AppData\Local\Temp\ipykernel_10984\2873132810.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_company["company_id"]=range(max_id+1,max_id+1+len(new_company))

    company_id                               company
0            1          Tac - Yellow Cab Association
1            2                             Flash Cab
2            3                            Globe Taxi
3            4                      Medallion Leasin
4            5                  Chicago Independents
5            6          Blue Ribbon Taxi Association
6            7            Tac - Checker Cab Dispatch
7            8                           5 Star Taxi
8            9     Transit Administrative Center Inc
9           10                          City Service
10          11                              Sun Taxi
11          12          Taxicab Insurance Agency Llc
12          13           Choice Taxi Association Inc
13          14         Chicago City Taxi Association
14          15         Taxicab Insurance Agency  LLC
15          16  Patriot Taxi Dba Peace Taxi Associat
16          17         312 Medallion Management Corp
17          18                       Chicago Taxicab
18          19           3556 - 36214 RC Andrews Cab
19          20        Star North Taxi Management Llc
20          21                               Top Cab
21          22                           Wolley Taxi
22          23                            Setare Inc
23          24        Tac - American United Dispatch
24          25                Tac - Yellow Non Color
25          26           Tac - Blue Diamond Dispatch
26          27                 Koam Taxi Association
27          28            5167 - 71969 5167 Taxi Inc
28          29                             U Taxicab
29          30           6574 - Babylon Express Inc.
30          31                     Metro Jet Taxi A.
31          32          4053 - 40193 Adwar H. Nikola
32          33                                     x
33          34                                     y