In [5]:
from datetime import datetime
from dateutil.relativedelta import relativedelta

import pandas as pd
pd.set_option("display.max_columns",30)
import requests

In [6]:
current_datetime=datetime.now() - relativedelta(months=2)
formatted_datetime=current_datetime.strftime("%Y-%m-%d")



url= (
    f"https://data.cityofchicago.org/api/v3/views/ajtu-isnz/query.json?app_token=ogjssL0qdXCJ16jANDq5lFDLc"
    f"&query=select * where trip_start_timestamp>='2024-02-16T00:00:00' AND trip_start_timestamp<='2024-02-16T23:59:59'"
)
response=requests.get(url)
data=response.json()

len(data)

15766

In [7]:
taxi_trips=pd.DataFrame(data)

taxi_trips.head()

,trip_id,taxi_id,trip_start_timestamp,trip_end_timestamp,trip_seconds,trip_miles,pickup_community_area,fare,tips,tolls,extras,trip_total,payment_type,company,pickup_centroid_latitude,pickup_centroid_longitude,pickup_centroid_location,:id,:version,:created_at,:updated_at,dropoff_community_area,dropoff_centroid_latitude,dropoff_centroid_longitude,dropoff_centroid_location,pickup_census_tract,dropoff_census_tract
0,fae40968253578fac8d7caab85a1e441e7c3fc85,d7a7bb002b49257d43e0f0c00702f1182ba37f9eda065c...,2024-02-16T23:45:00.000,2024-02-17T00:00:00.000,1634,16.21,76,40,9.2,1.5,4,55.2,Credit Card,Sun Taxi,41.980264315,-87.913624596,"{'type': 'Point', 'coordinates': [-87.91362459...",row-59sz~y6w8_2jdm,rv-2fww-x4s2~jape,2024-03-07T16:28:29.189Z,2024-03-07T16:28:29.189Z,NaN,NaN,NaN,NaN,NaN,NaN
1,7454f4377b06cdc2cb7a7de461363f46780c1b90,3b67c82e534b28c587042f6dab27152dff9f982cc7eaf3...,2024-02-16T23:45:00.000,2024-02-17T00:00:00.000,1058,9.65,8,24.44,6.24,0,0,30.68,Mobile,Sun Taxi,41.899602111,-87.633308037,"{'type': 'Point', 'coordinates': [-87.63330803...",row-xy3h~he79.3dci,rv-6dzd_bqr7~764p,2024-03-07T16:28:29.189Z,2024-03-07T16:28:29.189Z,77,41.9867118,-87.663416405,"{'type': 'Point', 'coordinates': [-87.66341640...",NaN,NaN
2,76c01d5bae9b0f61fe1f3103427211383071fa19,1f25a2b2c1cf1bd6ad6733bfa6eacddf5c9475102bfcd7...,2024-02-16T23:45:00.000,2024-02-17T00:30:00.000,2340,0,NaN,63,0,0,0,63,Cash,"Taxicab Insurance Agency, LLC",NaN,NaN,NaN,row-zwu3-xahc~n5pa,rv-6wyr-7h5k.gw33,2024-03-07T16:28:29.189Z,2024-03-07T16:28:29.189Z,NaN,NaN,NaN,NaN,NaN,NaN
3,78232da6c497bb68b8f94e958425a777de54bf3f,d49aa86282666bf46ee41b825c4697a6e18532cbcb484a...,2024-02-16T23:45:00.000,2024-02-17T00:00:00.000,600,1.6,28,8.25,0,0,1,9.25,Cash,Chicago City Taxi Association,41.874005383,-87.66351755,"{'type': 'Point', 'coordinates': [-87.66351754...",row-6zsa_2273~z5xb,rv-it7v_jm7v-wiuq,2024-03-07T16:28:29.189Z,2024-03-07T16:28:29.189Z,32,41.878865584,-87.625192142,"{'type': 'Point', 'coordinates': [-87.62519214...",NaN,NaN
4,79201d31fcb39be2cd4c055371bc9dc5ecfdce5a,b02980a1f1cf5e8f64e56a911bd2bc7e0fb733bf6e465f...,2024-02-16T23:45:00.000,2024-02-17T00:00:00.000,1113,12.04,76,31,10.65,0,4,46.15,Credit Card,Sun Taxi,41.980264315,-87.913624596,"{'type': 'Point', 'coordinates': [-87.91362459...",row-ufkx-9vjb-6s2x,rv-t6eg.7tdc~xnjw,2024-03-07T16:28:29.189Z,2024-03-07T16:28:29.189Z,21,41.938666196,-87.711210593,"{'type': 'Point', 'coordinates': [-87.71121059...",NaN,NaN

In [8]:
taxi_trips.tail()

,trip_id,taxi_id,trip_start_timestamp,trip_end_timestamp,trip_seconds,trip_miles,pickup_community_area,fare,tips,tolls,extras,trip_total,payment_type,company,pickup_centroid_latitude,pickup_centroid_longitude,pickup_centroid_location,:id,:version,:created_at,:updated_at,dropoff_community_area,dropoff_centroid_latitude,dropoff_centroid_longitude,dropoff_centroid_location,pickup_census_tract,dropoff_census_tract
15761,52253e7a95b9c66db60f861510bf5882f5fa11c6,8307cf9433f0293eee99c6944aeab484521d9cd9b1fce5...,2024-02-16T00:00:00.000,2024-02-16T00:00:00.000,6,0,24,10,0,0,0,10.5,Credit Card,City Service,41.901206994,-87.676355989,"{'type': 'Point', 'coordinates': [-87.67635598...",row-7jhs_zndz_mfeb,rv-evki.i8bg.crc3,2024-03-07T16:28:29.189Z,2024-03-07T16:28:29.189Z,24,41.901206994,-87.676355989,"{'type': 'Point', 'coordinates': [-87.67635598...",NaN,NaN
15762,4ecb9cf99bcf691a9e788205a1d1c145c41f39a5,922a0223b6c4173a158b0f1fed098dd8c6e2a303f520b2...,2024-02-16T00:00:00.000,2024-02-16T00:15:00.000,840,0,76,23,6.85,0,4,33.85,Credit Card,Taxi Affiliation Services,41.980264315,-87.913624596,"{'type': 'Point', 'coordinates': [-87.91362459...",row-i6rg.rs7g.g7ws,rv-pg4d-r55m-w7en,2024-03-07T16:28:29.189Z,2024-03-07T16:28:29.189Z,12,41.993930128,-87.758353588,"{'type': 'Point', 'coordinates': [-87.75835358...",NaN,NaN
15763,4ca1e47420dffe08fd941c419ae3189704e1fdad,f73d5459dcae455d9d7eb464fb7689b48cf9518d3cf1b7...,2024-02-16T00:00:00.000,2024-02-16T00:00:00.000,463,2.91,32,10.25,2,0,0,12.75,Credit Card,City Service,41.878865584,-87.625192142,"{'type': 'Point', 'coordinates': [-87.62519214...",row-4fq2-8u3v-u48a,rv-gxdy_82ps~y93i,2024-03-07T16:28:29.189Z,2024-03-07T16:28:29.189Z,31,41.850266366,-87.667569312,"{'type': 'Point', 'coordinates': [-87.66756931...",NaN,NaN
15764,462de8d7d1f10a1db475403cf725ee0e7a4d70ac,e5e1bb9c3329c0f9bd1f291cb9bbbb016731c148fefca8...,2024-02-16T00:00:00.000,2024-02-16T00:00:00.000,180,0.73,8,5,3,0,0,8.5,Credit Card,Flash Cab,41.899602111,-87.633308037,"{'type': 'Point', 'coordinates': [-87.63330803...",row-94gj.zqg7~xs8y,rv-irbm~e3vk_t3q2,2024-03-07T16:28:29.189Z,2024-03-07T16:28:29.189Z,32,41.878865584,-87.625192142,"{'type': 'Point', 'coordinates': [-87.62519214...",NaN,NaN
15765,44c0cb1bdacc382128091f2c2bcb1e8f390130ac,2ec5c47128a98f946f5f1382680e6e48752eb935542ad1...,2024-02-16T00:00:00.000,2024-02-16T00:15:00.000,716,2.93,32,11.25,2,0,0,13.75,Credit Card,Chicago Independents,41.878865584,-87.625192142,"{'type': 'Point', 'coordinates': [-87.62519214...",row-eve6.hg8s.mpk8,rv-frxr-hgfv_9xnb,2024-03-07T16:28:29.189Z,2024-03-07T16:28:29.189Z,28,41.874005383,-87.66351755,"{'type': 'Point', 'coordinates': [-87.66351754...",NaN,NaN

In [9]:
taxi_trips.sample(5)

,trip_id,taxi_id,trip_start_timestamp,trip_end_timestamp,trip_seconds,trip_miles,pickup_community_area,fare,tips,tolls,extras,trip_total,payment_type,company,pickup_centroid_latitude,pickup_centroid_longitude,pickup_centroid_location,:id,:version,:created_at,:updated_at,dropoff_community_area,dropoff_centroid_latitude,dropoff_centroid_longitude,dropoff_centroid_location,pickup_census_tract,dropoff_census_tract
3334,7427d4a5acf254d2825a6c970858aa2cd690e6a9,33d0b751a7c55e6c8ce21d8226710db0da56a644ed6d07...,2024-02-16T18:45:00.000,2024-02-16T19:15:00.000,1352,3.98,2,14.5,0,0,0,14.5,Prcard,Flash Cab,42.001571027,-87.695012589,"{'type': 'Point', 'coordinates': [-87.69501258...",row-jbns-eaci_5rx6,rv-j2e7_nru7.fqrx,2024-03-07T16:28:29.189Z,2024-03-07T16:28:29.189Z,3,41.96581197,-87.655878786,"{'type': 'Point', 'coordinates': [-87.65587878...",NaN,NaN
3932,308e7bf9c89d829215faa97daefea656d5994a74,763ae7383c3fd4eb95375759ee5d926e3309fa63656a57...,2024-02-16T18:15:00.000,2024-02-16T18:15:00.000,0,0,NaN,3.25,0.11,0,0,3.36,Credit Card,Taxi Affiliation Services,NaN,NaN,NaN,row-vmk8-afas~a22h,rv-ppae.rukp.u4gu,2024-03-07T16:28:29.189Z,2024-03-07T16:28:29.189Z,NaN,NaN,NaN,NaN,17031806600,17031806600
5279,7a8ce22023f9d3b69d6f78962902f3577d401df8,0e74ad3459f87717288898bd3fea44cbb0d2d2d9b9580e...,2024-02-16T17:00:00.000,2024-02-16T17:15:00.000,646,1.68,32,8.25,2,0,0,10.75,Credit Card,Chicago Independents,41.878865584,-87.625192142,"{'type': 'Point', 'coordinates': [-87.62519214...",row-2c8w~xzny~j42q,rv-kcd3-36hf-qki4,2024-03-07T16:28:29.189Z,2024-03-07T16:28:29.189Z,24,41.901206994,-87.676355989,"{'type': 'Point', 'coordinates': [-87.67635598...",NaN,NaN
2459,e8679ac82e329107a1ac9b08694ad2cb0decbfdb,b0c2db08b6f6bf8d19a6412bc3c5023d9810394b71d12f...,2024-02-16T19:30:00.000,2024-02-16T20:00:00.000,1242,4.9,32,16.75,0,0,0,16.75,Cash,Flash Cab,41.878865584,-87.625192142,"{'type': 'Point', 'coordinates': [-87.62519214...",row-49cm~gi2j~xxr4,rv-asnh.98ev_b3v6,2024-03-07T16:28:29.189Z,2024-03-07T16:28:29.189Z,38,41.812948939,-87.617859676,"{'type': 'Point', 'coordinates': [-87.61785967...",NaN,NaN
2127,7b046e88c4a3f8e188234d5344e2ce826c384d92,8dd990653cc2793d96b80ae45e928afc9a590b21b491ee...,2024-02-16T20:00:00.000,2024-02-16T20:00:00.000,464,1.41,32,7.25,1.31,0,1,10.06,Mobile,Sun Taxi,41.884987192,-87.620992913,"{'type': 'Point', 'coordinates': [-87.62099291...",row-r7c6.k32f-7qr9,rv-8un6.c8wh~izhd,2024-03-07T16:28:29.189Z,2024-03-07T16:28:29.189Z,32,41.880994471,-87.632746489,"{'type': 'Point', 'coordinates': [-87.63274648...",17031320100,17031839100

In [10]:
taxi_trips.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15766 entries, 0 to 15765
Data columns (total 27 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   trip_id                     15766 non-null  object
 1   taxi_id                     15766 non-null  object
 2   trip_start_timestamp        15766 non-null  object
 3   trip_end_timestamp          15766 non-null  object
 4   trip_seconds                15761 non-null  object
 5   trip_miles                  15766 non-null  object
 6   pickup_community_area       15346 non-null  object
 7   fare                        15740 non-null  object
 8   tips                        15740 non-null  object
 9   tolls                       15740 non-null  object
 10  extras                      15740 non-null  object
 11  trip_total                  15740 non-null  object
 12  payment_type                15766 non-null  object
 13  company                     15766 non-null  object
 14  pickup_centroid_latitude    15351 non-null  object
 15  pickup_centroid_longitude   15351 non-null  object
 16  pickup_centroid_location    15351 non-null  object
 17  :id                         15766 non-null  object
 18  :version                    15766 non-null  object
 19  :created_at                 15766 non-null  object
 20  :updated_at                 15766 non-null  object
 21  dropoff_community_area      14378 non-null  object
 22  dropoff_centroid_latitude   14423 non-null  object
 23  dropoff_centroid_longitude  14423 non-null  object
 24  dropoff_centroid_location   14423 non-null  object
 25  pickup_census_tract         5867 non-null   object
 26  dropoff_census_tract        5670 non-null   object
dtypes: object(27)
memory usage: 3.2+ MB

In [11]:
taxi_trips[taxi_trips["fare"].isna()].sample(5)

,trip_id,taxi_id,trip_start_timestamp,trip_end_timestamp,trip_seconds,trip_miles,pickup_community_area,fare,tips,tolls,extras,trip_total,payment_type,company,pickup_centroid_latitude,pickup_centroid_longitude,pickup_centroid_location,:id,:version,:created_at,:updated_at,dropoff_community_area,dropoff_centroid_latitude,dropoff_centroid_longitude,dropoff_centroid_location,pickup_census_tract,dropoff_census_tract
2490,be6ca7b65d45cf772e5febe7720565294fe51a3d,8c76eb82f069c0731a0049cb78898f02cc5ac6990244c9...,2024-02-16T19:30:00.000,2024-02-16T19:45:00.000,529,0.91,8,NaN,NaN,NaN,NaN,NaN,Cash,Sun Taxi,41.899155613,-87.626210532,"{'type': 'Point', 'coordinates': [-87.62621053...",row-9rsb.3qc9-3nzm,rv-57qn_mjf4.wubc,2024-03-07T16:28:29.189Z,2024-03-07T16:28:29.189Z,8,41.892042136,-87.63186395,"{'type': 'Point', 'coordinates': [-87.63186394...",17031081201,17031081700
13660,944589dbd26ddf5c3f98f547c955c1a8d86abdf7,3671b00a8d3d78e49e75a0eb9796fbfa1ab2e07b89d7ed...,2024-02-16T08:45:00.000,2024-02-16T09:00:00.000,761,1.89,28,NaN,NaN,NaN,NaN,NaN,Cash,Taxicab Insurance Agency Llc,41.885300022,-87.642808466,"{'type': 'Point', 'coordinates': [-87.64280846...",row-f5kd-cw7k~qh2d,rv-umt3~ngr9_yqfa,2024-03-07T16:28:29.189Z,2024-03-07T16:28:29.189Z,8,41.89503345,-87.619710672,"{'type': 'Point', 'coordinates': [-87.61971067...",17031280100,17031081401
1371,a5b5ed1d72b6aaeb25e1dfcf14f3c770dd0a100a,5e48748b582fe3c16baf5ac371a27773e8aef2927f3344...,2024-02-16T21:00:00.000,2024-02-16T21:00:00.000,268,1.28,33,NaN,NaN,NaN,NaN,NaN,Cash,Sun Taxi,41.849246754,-87.624135298,"{'type': 'Point', 'coordinates': [-87.62413529...",row-wwd6~qv8b-7ayr,rv-viad-fu78_ngjd,2024-03-07T16:28:29.189Z,2024-03-07T16:28:29.189Z,33,41.859349715,-87.617358006,"{'type': 'Point', 'coordinates': [-87.61735800...",17031841000,17031330100
12995,7f4682ba10e3796d56ad5c64b370dfee6aa23770,835869d6df51f9ec6e53cb4ac6a1f9e386c26f948cdcca...,2024-02-16T09:30:00.000,2024-02-16T10:00:00.000,1543,16.09,76,NaN,NaN,NaN,NaN,NaN,Cash,Taxicab Insurance Agency Llc,41.97907082,-87.903039661,"{'type': 'Point', 'coordinates': [-87.90303966...",row-kpwz_8ijg_b8ne,rv-75iz-mxht.3xvg,2024-03-07T16:28:29.189Z,2024-03-07T16:28:29.189Z,28,41.879255084,-87.642648998,"{'type': 'Point', 'coordinates': [-87.64264899...",17031980000,17031281900
13944,41d8834a404aae6247a953b1f0fe0b84caaab363,17561b2493682865136063664df49b8a74d4c7e67e0ccf...,2024-02-16T08:30:00.000,2024-02-16T08:30:00.000,333,0.6,8,NaN,NaN,NaN,NaN,NaN,Cash,Blue Ribbon Taxi Association,41.891971508,-87.612945414,"{'type': 'Point', 'coordinates': [-87.61294541...",row-v79m-r788~bz6s,rv-5k4w.w6ti.zya7,2024-03-07T16:28:29.189Z,2024-03-07T16:28:29.189Z,8,41.89503345,-87.619710672,"{'type': 'Point', 'coordinates': [-87.61971067...",17031081402,17031081401

### Transformation/Deal vith NaN values

In [12]:
taxi_trips.drop(["pickup_census_tract","dropoff_census_tract"],axis=1,inplace=True)

In [14]:
taxi_trips.drop(["pickup_centroid_location","dropoff_centroid_location"],axis=1,inplace=True)

In [ ]:
taxi_trips.dropna(inplace=True)   #ha valamelyik rekordban Nan van akkor az egész rekordot törli (adattisztítás)

In [17]:
taxi_trips.info()

<class 'pandas.core.frame.DataFrame'>
Index: 14254 entries, 1 to 15765
Data columns (total 23 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   trip_id                     14254 non-null  object
 1   taxi_id                     14254 non-null  object
 2   trip_start_timestamp        14254 non-null  object
 3   trip_end_timestamp          14254 non-null  object
 4   trip_seconds                14254 non-null  object
 5   trip_miles                  14254 non-null  object
 6   pickup_community_area       14254 non-null  object
 7   fare                        14254 non-null  object
 8   tips                        14254 non-null  object
 9   tolls                       14254 non-null  object
 10  extras                      14254 non-null  object
 11  trip_total                  14254 non-null  object
 12  payment_type                14254 non-null  object
 13  company                     14254 non-null  object
 14  pickup_centroid_latitude    14254 non-null  object
 15  pickup_centroid_longitude   14254 non-null  object
 16  :id                         14254 non-null  object
 17  :version                    14254 non-null  object
 18  :created_at                 14254 non-null  object
 19  :updated_at                 14254 non-null  object
 20  dropoff_community_area      14254 non-null  object
 21  dropoff_centroid_latitude   14254 non-null  object
 22  dropoff_centroid_longitude  14254 non-null  object
dtypes: object(23)
memory usage: 2.6+ MB

### Transformation/renaming

In [18]:
taxi_trips.rename(columns={"pickup_community_area":"pickup_community_area_id",
                           "dropoff_community_area":"dropoff_community_area_id"},inplace=True)

In [19]:
taxi_trips.columns

Index(['trip_id', 'taxi_id', 'trip_start_timestamp', 'trip_end_timestamp',
       'trip_seconds', 'trip_miles', 'pickup_community_area_id', 'fare',
       'tips', 'tolls', 'extras', 'trip_total', 'payment_type', 'company',
       'pickup_centroid_latitude', 'pickup_centroid_longitude', ':id',
       ':version', ':created_at', ':updated_at', 'dropoff_community_area_id',
       'dropoff_centroid_latitude', 'dropoff_centroid_longitude'],
      dtype='object')

###Trasformation/create helper column for weather data

In [20]:
taxi_trips["trip_start_timestamp"]=pd.to_datetime(taxi_trips["trip_start_timestamp"])

In [23]:
taxi_trips["datetime_for_weather"]=taxi_trips["trip_start_timestamp"].dt.floor("h")   
#az adatok negyedórásak, órássa alakítja hogy joinolni lehessen a weather adattal (ponots egyezés szükséges)

###check: join taxi and weather data